### ISSUE TITLE
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by Shinya754** [RjDuan/AdvDrop#21]
@RjDuan  您好！首先感谢您的工作！
我在按照README.md中的指示运行您提供的代码（infod_sample.py）时遇到了这个问题：

```
D:\Program Files\Anaconda3\envs\pytorch\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\Program Files\Anaconda3\envs\pytorch\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Iter:  0
Traceback (most recent call last):
  File "D:\CCCCCCCCCCCCCCCCCCC\Python for PyCharm\AdvDrop\AdvDrop-main\infod_sample.py", line 201, in <module>
    attack = InfoDrop(resnet_model, batch_size=batch_size, q_size=q_size, steps=150, targeted=True)
  File "D:\CCCCCCCCCCCCCCCCCCC\Python for PyCharm\AdvDrop\AdvDrop-main\infod_sample.py", line 55, in __init__
    self.q_tables = {"y": torch.from_numpy(q_ini_table),
  File "D:\Program Files\Anaconda3\envs\pytorch\lib\site-packages\torchattacks\attack.py", line 496, in __setattr__
    for num, value in enumerate(get_all_values(value)):
  File "D:\Program Files\Anaconda3\envs\pytorch\lib\site-packages\torchattacks\attack.py", line 488, in get_all_values
    yield from get_all_values(item, stack)
  File "D:\Program Files\Anaconda3\envs\pytorch\lib\site-packages\torchattacks\attack.py", line 482, in get_all_values
    if (items not in stack):
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

我发现已经关闭的issue中有一个人遇到了和我一样的的问题，但是他没有说明具体的解决方法，因此我重新开了一个issue。
我使用的软件包版本：
python                        3.9.16
torch                           1.13.1+cu116
numpy                        1.23.5
torchattacks                3.4.0

希望能够得到您的解答！

**Comment by RjDuan** [comment]
可否麻烦您打印一下q_ini_table 我看一下？

夤夜 ***@***.***> 于2023年5月18日周四 16:56写道：

**Comment by Shinya754** [comment]
@RjDuan  好的，我将打印代码添加在了`class InfoDrop(Attack):`的`__init__`方法的`self.q_tables = {"y": torch.from_numpy(q_ini_table),`语句之前：
```
        print(q_ini_table)
        print(type(q_ini_table))
        print(q_ini_table.shape)
```
然后得到了以下输出：
```
[[[[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  ...

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]]


 [[[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  ...

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]]


 [[[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  ...

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]]


 ...


 [[[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  ...

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]]


 [[[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  ...

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]]


 [[[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  ...

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]

  [[40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   ...
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]
   [40. 40. 40. ... 40. 40. 40.]]]]
<class 'numpy.ndarray'>
(20, 784, 8, 8)
```

**Comment by asif-hanif** [comment]
Hi @Shinya754 There is an issue with `torchattacks` __init__() function. For some reason, it does not let create a dictionary as its attribute e.g. `self.some_dict = {key_1:val_1, key_2:val_2, key_3:val_3}` where `val_i` is a numpy array. 

As a workaround, you can use following method which worked in my case:

```
self.some_dict = {}
self.some_dict[key_1] = val_1
self.some_dict[key_2] = val_2
self.some_dict[key_3] = val_3
```

**Comment by Shinya754** [comment]
Hi @asif-hanif ,Thank you for your help! I really appreciate it. You solved my problem.

Also, for developers using a similar version of the software package I listed above, if you get an error at line 97 of `infod_sample.py`, try modifying `adv_cost = adv_loss(outputs, labels)` to `adv_cost = adv_loss(outputs, labels.to(torch.long))`.

**Comment by RjDuan** [comment]
Thanks a lot for your help!

Asif Hanif ***@***.***> 于2023年5月22日周一 05:02写道：

**Comment by deepai-lab** [comment]
I also faced the same error. How you solved @Shinya754 ? Can you please share the file where you have changed?

**Comment by Shinya754** [comment]
> I also faced the same error. How you solved @Shinya754 ? Can you please share the file where you have changed?

Hi, @deepai-lab! Based on **asif-hanif**'s tips, I changed the following lines in "infod_sample.py" 

https://github.com/RjDuan/AdvDrop/blob/35ceeb0e1c4b258bf3995302fbce9f13b39860f0/infod_sample.py#L53-L55
to
```python
        self.q_tables = {}
        self.q_tables["y"] = torch.from_numpy(q_ini_table)
        self.q_tables["cb"] = torch.from_numpy(q_ini_table)
        self.q_tables["cr"] = torch.from_numpy(q_ini_table)
``` 


In addition, you may need to modify this line (if you are using a higher version of Python)
https://github.com/RjDuan/AdvDrop/blob/35ceeb0e1c4b258bf3995302fbce9f13b39860f0/infod_sample.py#L192
to
```python
        images, labels = next(normal_iter)
```
