### ISSUE TITLE
张量的布尔值不明确

### ISSUE THREAD

**Issue by asbzz** [RjDuan/AdvDrop#22]
(advdrop) PS E:\TEST\AdvDrop> python infod_sample.py
Iter:  0
Traceback (most recent call last):
  File "infod_sample.py", line 200, in <module>
    attack = InfoDrop(resnet_model, batch_size=batch_size, q_size=q_size, steps=150, targeted=True)
  File "infod_sample.py", line 57, in __init__
    "cr": torch.from_numpy(q_ini_table)}
  File "D:\Anaconda3\envs\advdrop\lib\site-packages\torchattacks\attack.py", line 563, in __setattr__
    for num, value in enumerate(get_all_values(value)):
  File "D:\Anaconda3\envs\advdrop\lib\site-packages\torchattacks\attack.py", line 555, in get_all_values
    yield from get_all_values(item, stack)
  File "D:\Anaconda3\envs\advdrop\lib\site-packages\torchattacks\attack.py", line 549, in get_all_values
    if items not in stack:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

**Comment by asbzz** [comment]
你好，请问你们的实验中有出现这样的问题吗？我应该怎么解决它？

**Comment by huwenfeng233** [comment]
您好，请问您找到解决方法了吗？

**Comment by asbzz** [comment]
#21 用这个方法可以解决
