### ISSUE TITLE
OSError: image file is truncated

### ISSUE THREAD

**Issue by zhoufengfan** [RjDuan/AdvDrop#5]
After I ran `python infod_sample.py`, it ran normally in the beginning. However, there occurred this error when `iter` is 48:
```
Step:  100   Loss:  7.811537265777588   Current Suc rate:  0.2
Step:  110   Loss:  7.403205871582031   Current Suc rate:  0.2
Step:  120   Loss:  7.0217485427856445   Current Suc rate:  0.2
Step:  130   Loss:  6.647172451019287   Current Suc rate:  0.2
Step:  140   Loss:  6.154144763946533   Current Suc rate:  0.25
Current suc. rate:  0.303125
Iter:  48
Traceback (most recent call last):
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/PIL/I                          mageFile.py", line 237, in load
    s = read(self.decodermaxblock)
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/PIL/P                          ngImagePlugin.py", line 896, in load_read
    cid, pos, length = self.png.read()
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/PIL/P                          ngImagePlugin.py", line 162, in read
    length = i32(s)
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/PIL/_                          binary.py", line 75, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking                           4 bytes at offset 0 (actual buffer size is 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "infod_sample.py", line 191, in <module>
    images, labels = normal_iter.next()
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/torch                          /utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/torch                          /utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/torch                          /utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/torch                          /utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/torch                          vision/datasets/folder.py", line 151, in __getitem__
    sample = self.loader(path)
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/torch                          vision/datasets/folder.py", line 188, in default_loader
    return pil_loader(path)
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/torch                          vision/datasets/folder.py", line 170, in pil_loader
    return img.convert('RGB')
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/PIL/I                          mage.py", line 904, in convert
    self.load()
  File "/home/miniconda3/envs/pytorch17/lib/python3.8/site-packages/PIL/I                          mageFile.py", line 243, in load
    raise OSError("image file is truncated") from e
OSError: image file is truncated
```

Can anyone help me?

Thanks a lot.

**Comment by RjDuan** [comment]
Hi there,   it seems the error is caused by "incorrect image file type"  or "broken image file".
Which dataset do you use?  
Delete ".DS_Store" if exists in the image dataset directory.

**Comment by zhoufengfan** [comment]
Thanks for your response.

We used the same data downloaded from the google driver in the `README.md` as the dataset. There is no `.DS_Store` in the image dataset directory.

Our PyTorch version is `1.7.1+cu101`. We run our experiment in a `TITAN XP` GPU. Our operation system is ubuntu16.04.

**Comment by RjDuan** [comment]
Hi, I ran the code but  the same problem is not found ;(
But I noticed another problem: a recent change results in a low success
rate (so sorry!) . I have updated the infod_sample.py.
Still, I think the problem should be caused by the dataset,  so I add a
simple data processing function for the dataset.
Please update the "infod_sample.py"  and  "utils.py".
Hope it will help.

zhoufengfan ***@***.***> 于2021年9月12日周日 下午7:51写道：

**Comment by zhoufengfan** [comment]
I have pulled the latest code, but the error still occurred. After I added these codes at the beginning of `infod_sample.py`, the error vanished:
``` python
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
The end of the print is:
```
Iter:  49
Step:  0   Loss:  21.456790924072266   Current Suc rate:  0.0
Step:  10   Loss:  10.450942993164062   Current Suc rate:  0.05
Step:  20   Loss:  5.52895975112915   Current Suc rate:  0.1
Step:  30   Loss:  2.497077226638794   Current Suc rate:  0.45000002
Step:  40   Loss:  0.989791989326477   Current Suc rate:  0.75
Step:  50   Loss:  0.3940030634403229   Current Suc rate:  0.90000004
End at step 53 with suc. rate 1.0
Current suc. rate:  0.997
Avg suc rate: 0.99700 +/- 0.00173

Process finished with exit code 0
```
A suggestion:

Add these python codes at the beginning of `infod_sample.py`.

Thanks.
